version: '3.9'


services:
  web:
    container_name: news_website_prod
    build: .
    command: gunicorn news_website.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      ./.env.prod
    depends_on:
      - db

  db:
    image: postgres
    container_name: news_db_prod
    volumes:
      - news_db:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db

volumes:
  prod_news_db: